tools/cloudbuild-artifacts.yaml
tools/package.sh

This generates artifacts to a GCS bucket that can be used for testing.
It is not intended to be used on PRs until they are merged.
------
This is intended to simplify the testing process at step 2 of go/grpc/td-grpc-bootstrap-release
I couldn't bring myself to setup Kokoro. Cloud Build actually turned out much easier to work with. The basic premise of Cloud Build is you have the source code available and then you run commands on it, but you can only run commands via containers. The containers have access to the source, so any modifications/additions to the source directory will be kept after the container returns.
Tested with: `gcloud builds submit --config tools/cloudbuild-artifacts.yaml --substitutions=COMMIT_SHA=IMAGINETHISISASHA`. The COMMIT_SHA is only automatically set via a push …

Add Cloud Build build-on-merge

---

go.mod
go.sum
main_test.go

Gets us to "28.9% of statements", which is pathetic, but sort of
expected for a command line tool like this. main() and getHostIp() are
entirely uncovered.
-------------------
While everything else in the repo is trivial, I wouldn't be surprised if something in these tests strikes you as wrong/needing improvement. That said, they're still close to trivial.

Add unit tests for the "happy" paths

---

go.mod
go.sum
main.go
main_test.go

This change makes the bootstrap generator emit the file_watcher plugin configuration by default. Currently there are no flags added to control this behavior. I can add them if we think it is necessary.

Emit file_watcher plugin configuration with default values

---

main.go
main_test.go

This value will be used as the `id` in the `resource_names` field of the LDS request, with `context_params` containing the listening IP:Port.

Add support for "grpc_server_resource_name_id" field

---

main.go
main_test.go

We are interested in the following pieces of information in the `Node` proto:
- network name
- project number
- local IP
- a unique node id
Today (for v2 implementation in TD), these are conveyed as follows:
- local IP and unique node id are encoded in `node.id`
- network and project are sent as `node.metadata` entries
Going forward, we want to do the following:
- Pass network, project and unique node id in the `node.id` field in the format: `projects/{project number}/networks/{network name}/nodes/{id}`
- also continue to send network and project as `node.metadata` entries
- send local IP in `network.metadata` with key `INSTANCE_IP`

Update Node proto to work with v2 and v3 xDS implementations in TD.

---

main.go
main_test.go

This is required because Zatar allows the user to mount the volume with secrets at a location of their liking.

Make directory containing secrets configurable

---

main.go

security is still not considered `stable`

don't emit security configs by default

---

deployment_info.go
go.mod
go.sum
main.go
main_test.go

Summary of changes
- Identify the deployment type by talking to the Metadata server
- Add command line flags for deployment information that we plan to add to the `Node` metadata
- Talk to Metadata server and retrieve deployment information when the same is not specified on the command line

Add deployment info as part of Node metadata

---

main.go
main_test.go

The AppNet APIs introduce a `scope` field independent of VPC network. This PR introduces a flag enabling the bootstrap file to select a particular scope.

Add --config-scope-experimental flag

---

main.go

8765051 enabled the security output by default, but didn't end up
stabilizing other related flags. Node-metadata is used by endpoint
policies to select backends and the x8s security component allows
configuring secrets-dir (although we generally expect it to be the
default).
FYI: we'll be doing a release for this change, as node-metadata is
important enough to warrant it. Srini gave the okay.
CC @sanjaypujare

Stabilize security flags

---

main.go
main_test.go

App Net will no longer be supporting xDS V2, so we drop the v2-compatible method of supplying scope in the bootstrap.
@ejona86 @easwars

Drop xDS v2 support from bootstrap generator

---

README.md

The motivation of this PR is https://hub.docker.com/r/sevki/td-grpc-bootstrap. I think we should be explicit about the GCR maintained by us officially.
@ejona86

Update REAME: link our public Docker image && a minimum usage guide

---

main.go
main_test.go

This also includes a change from a "scope:" prefix in the node ID to a "mesh:" prefix instead.

Rename --config-scope-exerimental to --config-mesh-experimental

---

.github/workflows/testing.yml
.gitignore
tools/cloudbuild-artifacts.yaml

Go 1.18 includes VCS information within the binary so it is easy to
determine the git commit the binary was built with using `go version
-m`. Go considers the VCS modified if there are unknown files, so add
gitignore to avoid causing the build to be considered dirty.

Use Go 1.18 in CI

---

tools/cloudbuild-artifacts.yaml

This fixes a regression introduced in 9f045adb that broke the Cloud
Build CI:
```
Step #0: go: missing Git command. See https://golang.org/s/gogetcmd
Step #0: error obtaining VCS status: exec: "git": executable file not found in $PATH
Step #0: 	Use -buildvcs=false to disable VCS stamping.
```
In Go 1.18 the Go command will invoke the git command to include VCS
information inside the binary. We want that functionality, so we don't
want to pass `-buildvcs=false`. The non-Alpine container includes the
git command.

Use non-Alpine image on Cloud Build CI

---

main.go
main_test.go

as per a47 xDS Federation [spec](https://github.com/grpc/proposal/blob/master/A47-xds-federation.md) we need to add the authorities field. 
For the authorities field, we want two entries:
+ Empty string: This will be used for all new style resource names which contain no authority
+ "trafficdirector.googleapis.com:443": This is for new style resource names which explicitly specify TD
For both these entries, we will leave the value empty or {}. That way, they will still both end up talking to TD with the server config specified by the top-level
Note that in `authorities` map authority name's value is empty. This is to force default to the `xds_server_uri` specified in the top level `xds_servers` field. 
Fixes _task 1_ in #32

Changes to support xDS Federation

---

main.go
main_test.go

As part of xds federation changes, we need to add support to the bootstrap generator to add c2p authority to the config. This change addresses that. 
1. add C2P TD authority option using a `include-directpath-authority-experimental` flag 
2. add additional logic to the bootstrap generator to query `http://metadata.google.internal/computeMetadata/v1/instance/network-interfaces/0/ipv6s` and set the `TRAFFICDIRECTOR_DIRECTPATH_C2P_IPV6_CAPABLE` to true or false, in node metadata
Part of #32

Add support to include c2p authority

---

main.go
main_test.go

As per [A47](https://github.com/grpc/proposal/blob/master/A47-xds-federation.md), a new field called `client_listener_resource_template` has been added to the `authorities` field. 
In a C2P directPath use case we want the `C2PAuthority` to include a `client_listener_resource_template` with the new xdstp style name. The Url to be used has been referenced from [here](https://docs.google.com/document/d/1xwuSTdtV4I8MXXO_A0TIGAYtysbkothSBoH5xVuyr5I/edit#heading=h.ykp0ozda8boq). 
Also modifying existing unit test.

Use xdstp name for client listener resource template name for C2P

---

main.go
main_test.go

We added the `client_default_listener_resource_name_template` field to the bootstrap config as per  [A47](https://github.com/grpc/proposal/blob/master/A47-xds-federation.md). 
We would like to have the option for the bootstrap generator to add field to the authorities with the xdstp style name for listener resources with TD c2p authority name (when used in conjunction with `includeFederationSupport` and `includeDirectPathAuthority` flags. 
This PR adds a flag to support this. 
+ `trafficdirector.googleapis.com:443` seems wrong and should be `traffic-director-global.xds.googleapis.com` instead
+ When we do a lookup for which server to request for a CDS resource, it seems we wouldn't find a control plane

Add flag to use xdstp name for client listener resource template name

---

main.go
main_test.go

Now in DIrectpath (C2P) usecases, `ignore_resource_deletion` server feature can always be set.

ignore_resource_deletion server feature is always set in directpath use-cases

---

main.go
main_test.go

The LDS resource name format was incorrect. The correct format as per the xDS TD documentation is 
```
xdstp://<authority>/envoy.config.listener.v3.Listener/<project_number>/<(network)|(mesh:mesh_name)>/id
```
This change fixes the format.

Fix LDS resource name format for TD authority

---

main.go
main_test.go

The empty authority is not being used as per [A47](https://github.com/grpc/proposal/blob/master/A47-xds-federation.md). This change removes that and also nixes a flag which would then become unused.

remove empty string authority from authorities map

---

main.go

This change enables xdstp style names for P2C and C2P cases by default.

Enable xdstp style name by default for P2C and C2P cases

---

tools/cloudbuild-artifacts.yaml

Since there are 2 packages now we need to use `go build .` to create the binary. `go test` still need to run for all the sub directories

Update cloudbuild-artificats.yaml build step

---

main.go
main_test.go

Fixes #47 
The value of `--locality-zone` flag has been used to auto generate Mesh ID as cluster location. However usage of zone to always generate the mesh ID is not correct. The location of the GKE cluster could either be either zonal or regional based on the deployment. 
Hence we need to introduce a new flag  `--gke-location-experimental` to determine the location of the GKE cluster. The flag is Ignored if not used with `--generate-mesh-id-experimental`. If unset the location of the GKE cluster can be determined using the following GKE metadata server (MDS) API `http://metadata.google.internal/computeMetadata/v1/instance/attributes/cluster-location`. 
For existing PSM users of the generator version https://github.com/GoogleCloudPlatform/traffic-director-grpc-boostrap/releases/v1.15.0 …

add --gke-location-experimental to generate mesh ID for both regional and zonal GKE clusters

---

main.go

Changes: 
- Remove deprecated usage of [io/ioutil.ReallAll](pkg.go.dev/io/ioutil#ReadAll) with io.ReadAll
- Remove unused helper function

replace deprecated ioutil.ReadAll with io.ReadAll

---

.github/workflows/testing.yml
main.go
main_test.go
tools/cloudbuild-artifacts.yaml

For some of the features in flight, it would be nice to determine the version of the generator used by looking at the Node metadata that is being passed to TD. This change add a new value to Node.Metadata keyed with `TRAFFICDIRECTOR_GRPC_BOOTSTRAP_GENERATOR_SHA` and is plumbed the git commit ID at HEAD.

add generator commit hash to node metadata

---

main.go
main_test.go

While testing the generator prior to releasing the new `--gke-cluster-location-experimental`, I found that there was a typo in the MDS API endpoint used by `getClusterLocality`. 
I've tested the new changes in a Kubernetes container, please see below 
<details>
<summary>Testing details</summary>
Project name: arvindbright-k8n-test
Cluster name: arvindbright-test-ssa
Pod name: psm-grpc-client-8568fccdc6-44qht
```sh
root@psm-grpc-client-8568fccdc6-44qht:/traffic-director-grpc-bootstrap# ./td-grpc-bootstrap --generate-mesh-id-experimental
{
"xds_servers": [
{
"server_uri": "trafficdirector.googleapis.com:443",
"channel_creds": [
{
"type": "google_default"
}
],
"server_features": [
"xds_v3"
]
}
],
"authorities": {
"traffic-director-c2p.xds.googleapis.com": {
"xds_servers": [
{
"server_uri": …
```

Fix MDS url for getClusterLocality

---

main.go
main_test.go

As part of the next release, we want to stabilize flags that were introduced as part of CSM release and have been tested. The shape of these flags are not expected to change since they define very specific GKE / CSM related attributes. The flags that are stabilize are the following: 
- `gke-cluster-name`
- `config-mesh`
- `generate-mesh-id`
I tested to make sure we have backwards compatibility to the `-experimental` flags. 
<details>
<summary>Test details</summary>
Project name: arvindbright-k8n-test
Cluster name: arvindbright-test-ssa
Pod name: psm-grpc-client-8568fccdc6-44qht
```sh
root@psm-grpc-client-8568fccdc6-44qht:/traffic-director-grpc-bootstrap# ./td-grpc-bootstrap --generate-mesh-id
{
"xds_servers": [
{
"server_uri": "trafficdirector.googleapis.com:443",
"channel_creds": [
{ …
```

Stabilize GKE related flags

---

main.go
main_test.go

`--include-xdstp-name-in-lds-experimental` currently only adds in the TDOM authority to the authorities map. For xDS dial targets without an authority to default to the new xDSTP style name and use the TDOM authority, the flag should add `client_default_listener_resource_name_template` to the config.
If a gRPC client channel is created for `xds:server.example.com`
- The target URI specifies no authority, so we use the `client_default_listener_resource_name_template` field. The resulting resource name will be `xdstp://traffic-director-global.xds.googleapis.com/envoy.config.listener.v3.Listener/123456789012345/thedefault/server.example.com`.
- The resource name specifies the TDOM authority, so that's the entry we use from the `authorities` map.
- We do not use the …

add ClientDefaultListenerResourceNameTemplate when used with --include-xdstp-name-in-lds-experimental

---

main.go

This is the next part of stabilizing the `include-xdstp-name-in-lds-experimental` flag  that was introduced in https://github.com/GoogleCloudPlatform/traffic-director-grpc-bootstrap/pull/35 per the steps mentioned in #57 .
Testing: 
Setup Proxyless Service Mesh setup using a gRPC Server 
1. default behavior (i.e., not specifying the flag which implies: `include-xdstp-name-in-lds-experimental=true`)
1.  dial target w/o authority: 
`xds:///helloworld.default.svc.cluster.local:50051` 
```
./grpcurl --plaintext   -d '{"name": "world"}'   xds:///helloworld.default.svc.cluster.local:50051  helloworld.Greeter/SayHello
{
"message": "Hello from psm-grpc-server-57d8c669b9-wz6fh world"
}
```
1. dial target w/ authority: 
`xds://traffic-director-global.xds.googleapis.com/helloworld.default.svc.cluster …

set include-xdstp-name-in-lds-experimental flag to true by default

---

main.go

GKE-NAMESPACE is a user input field and would be empty if not specified. This change would make this entry optional if the input value were empty.

make GKE-NAMESPACE an optional entry in TRAFFIC_DIRECTOR_CLIENT_ENVIRONMENT Node Metadata

---

main.go
main_test.go

In order to address use-cases where authority rewriting may not be acceptable from a security perspective, adding a new server feature to the bootstrap config. The server feature is  specfied via the server_features field described in [gRFC A30](https://github.com/grpc/proposal/blob/master/A30-xds-v3.md). The feature is the string trusted_xds_server. (Note that the name is intentionally fairly general, since it may be used to trigger other security-sensitive functionality in the future.)

Add trusted_xds_server server feature for TD

---

Dockerfile

This is to make scanning tools happy, that only know about a limited number of distros (b/366296183). Previously the image wasn't a proper OCI because it lacked os-release and such, but that also isn't the root of the problem. This new base image has ca-certificates, /tmp, and tzdata, none of which do we actually want to use. This appears to be the lowest-dependency base image understood by the scanning tool.
CC @arvindbr8

Use distroless/static as base image

---

main_test.go

- Use `http.StatusForbidden` instead of `403`
- Remove redundant return

minor: address go-staticcheck warnings in main_test.go
